




using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;
using InternConnect_Backend.Models;
using InternConnect_Backend.Data;

namespace Backend_InternPortal.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class ActivitiesController : ControllerBase
    {
        private readonly ApplicationDbContext _context;
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly IConfiguration _config;

        public ActivitiesController(ApplicationDbContext context, IHttpClientFactory httpClientFactory, IConfiguration config)
        {
            _context = context;
            _httpClientFactory = httpClientFactory;
            _config = config;
        }

        [HttpPost("generate")]
        public async Task<IActionResult> GenerateActivities([FromBody] GenerateActivitiesRequest request)
        {
            // 1. Fetch complete profile
            var profile = await _context.Profiles
                .Include(p => p.Educations)
                .Include(p => p.Skills)
                .Include(p => p.Projects)
                .Include(p => p.Achievements)
                .FirstOrDefaultAsync(p => p.UserId == request.UserId);

            if (profile == null)
                return NotFound("Profile not found for given UserId");


            // 🔹 Remove existing activities for this user
            var existingActivities = _context.Activities.Where(a => a.UserId == request.UserId);
            if (existingActivities.Any())
            {
                _context.Activities.RemoveRange(existingActivities);
                await _context.SaveChangesAsync();
            }


            // 2. Serialize profile safely
            var profileJson = JsonConvert.SerializeObject(profile,
                Formatting.None,
                new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });

            // 3. Build user prompt
            var userPrompt = $@"
Generate {request.Count} career development activities for the following profile.
Each activity must follow this JSON schema and keep ActivityId = 0 everytime :

[
  {{
    ""ActivityId"": 0,
    ""UserId"": {request.UserId},
    ""StepNumber"": number from 1 to {request.Count},
    ""Heading"": ""string"",
    ""Description"": ""string"",
    ""ResourceLink"": ""string"",
    ""EstimatedTime"": ""string"",
    ""Status"": ""Pending""
  }}
]

Profile Data: {profileJson}
Career Goal: {profile.CareerGoal}
";

            // 4. Call Gemini API (correct payload)
            var geminiUrl = $"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={_config["Gemini:ApiKey"]}";

            var payload = new
            {
                contents = new[]
                {
                    new
                    {
                        parts = new[]
                        {
                            new { text = userPrompt }
                        }
                    }
                }
            };

            var httpClient = _httpClientFactory.CreateClient();
            var httpContent = new StringContent(JsonConvert.SerializeObject(payload), Encoding.UTF8, "application/json");

            var response = await httpClient.PostAsync(geminiUrl, httpContent);

            if (!response.IsSuccessStatusCode)
            {
                var errorBody = await response.Content.ReadAsStringAsync();
                return StatusCode((int)response.StatusCode, $"Failed to generate activities from Gemini API. Response: {errorBody}");
            }

            var responseString = await response.Content.ReadAsStringAsync();
            dynamic geminiResponse = JsonConvert.DeserializeObject(responseString);

            if (geminiResponse?.candidates == null || geminiResponse.candidates.Count == 0)
                return BadRequest("No activities generated by Gemini");

            string aiContent = geminiResponse.candidates[0].content.parts[0].text.ToString();

            // 5. Clean AI response (strip ```json fences if present)
            aiContent = aiContent.Trim();
            if (aiContent.StartsWith("```"))
            {
                int firstNewLine = aiContent.IndexOf('\n');
                int lastFence = aiContent.LastIndexOf("```");
                if (firstNewLine >= 0 && lastFence > firstNewLine)
                    aiContent = aiContent.Substring(firstNewLine + 1, lastFence - firstNewLine - 1).Trim();
            }

            // 6. Deserialize into Activities
            List<Activity>? activities;
            try
            {
                activities = JsonConvert.DeserializeObject<List<Activity>>(aiContent);
            }
            catch (JsonException ex)
            {
                return BadRequest("Failed to parse activities from Gemini response. AI response: " + aiContent + " | Error: " + ex.Message);
            }

            if (activities == null || !activities.Any())
                return BadRequest("No activities parsed from AI response");

            // 7. Ensure UserId & defaults
            foreach (var activity in activities)
            {
                activity.UserId = request.UserId;
                if (string.IsNullOrWhiteSpace(activity.Status))
                    activity.Status = "Pending";
            }

            // 8. Save activities to DB
            _context.Activities.AddRange(activities);
            await _context.SaveChangesAsync();

            // 9. Return saved activities
            return Ok(activities);
        }




        [HttpGet("{userId}")]
        public async Task<IActionResult> GetActivitiesByUserId(int userId)
        {
            var activities = await _context.Activities
                .Where(a => a.UserId == userId)
                .OrderBy(a => a.StepNumber)
                .ToListAsync();

            if (activities == null || !activities.Any())
                return NotFound($"No activities found for UserId {userId}");

            return Ok(activities);
        }

    }

    public class GenerateActivitiesRequest
    {
        public int UserId { get; set; }       // The user for whom activities will be generated
        public int Count { get; set; } = 5;   // Number of activities to generate (default 5)
    }
}
