using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;
using InternConnect_Backend.Models;
using InternConnect_Backend.Data;

namespace Backend_InternPortal.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class CareerTipsController : ControllerBase
    {
        private readonly ApplicationDbContext _context;
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly IConfiguration _config;

        public CareerTipsController(ApplicationDbContext context, IHttpClientFactory httpClientFactory, IConfiguration config)
        {
            _context = context;
            _httpClientFactory = httpClientFactory;
            _config = config;
        }

        [HttpPost("generate")]
        public async Task<IActionResult> GenerateCareerTips([FromBody] GenerateCareerTipsRequest request)
        {
            // 1. Fetch complete profile
            var profile = await _context.Profiles
                .Include(p => p.Educations)
                .Include(p => p.Skills)
                .Include(p => p.Projects)
                .Include(p => p.Achievements)
                .FirstOrDefaultAsync(p => p.UserId == request.UserId);

            if (profile == null)
                return NotFound("Profile not found for given UserId");

            // 🔹 Remove existing career tips for this user
            var existingTips = _context.CareerTips.Where(ct => ct.UserId == request.UserId);
            if (existingTips.Any())
            {
                _context.CareerTips.RemoveRange(existingTips);
                await _context.SaveChangesAsync();
            }

            // 2. Serialize profile safely
            var profileJson = JsonConvert.SerializeObject(profile,
                Formatting.None,
                new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });

            // 3. Build user prompt
            var userPrompt = $@"
Generate {request.Count} career tips for the following profile.
Each tip must follow this JSON schema and tip should have 10 to 15 words and keep CareerTipId = 0 every time :  

[
  {{
    ""CareerTipId"": 0,
    ""UserId"": {request.UserId},
    ""Description"": ""string""
  }}
]

Profile Data: {profileJson}
Career Goal: {profile.CareerGoal}
";

            // 4. Call Gemini API
            var geminiUrl = $"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={_config["Gemini:ApiKey"]}";

            var payload = new
            {
                contents = new[]
                {
                    new
                    {
                        parts = new[]
                        {
                            new { text = userPrompt }
                        }
                    }
                }
            };

            var httpClient = _httpClientFactory.CreateClient();
            var httpContent = new StringContent(JsonConvert.SerializeObject(payload), Encoding.UTF8, "application/json");

            var response = await httpClient.PostAsync(geminiUrl, httpContent);

            if (!response.IsSuccessStatusCode)
            {
                var errorBody = await response.Content.ReadAsStringAsync();
                return StatusCode((int)response.StatusCode, $"Failed to generate career tips from Gemini API. Response: {errorBody}");
            }

            var responseString = await response.Content.ReadAsStringAsync();
            dynamic geminiResponse = JsonConvert.DeserializeObject(responseString);

            if (geminiResponse?.candidates == null || geminiResponse.candidates.Count == 0)
                return BadRequest("No career tips generated by Gemini");

            string aiContent = geminiResponse.candidates[0].content.parts[0].text.ToString();

            // 5. Clean AI response (strip ```json fences if present)
            aiContent = aiContent.Trim();
            if (aiContent.StartsWith("```"))
            {
                int firstNewLine = aiContent.IndexOf('\n');
                int lastFence = aiContent.LastIndexOf("```");
                if (firstNewLine >= 0 && lastFence > firstNewLine)
                    aiContent = aiContent.Substring(firstNewLine + 1, lastFence - firstNewLine - 1).Trim();
            }

            // 6. Deserialize into CareerTips
            List<CareerTip>? careerTips;
            try
            {
                careerTips = JsonConvert.DeserializeObject<List<CareerTip>>(aiContent);
            }
            catch (JsonException ex)
            {
                return BadRequest("Failed to parse career tips from Gemini response. AI response: " + aiContent + " | Error: " + ex.Message);
            }

            if (careerTips == null || !careerTips.Any())
                return BadRequest("No career tips parsed from AI response");

            // 7. Ensure UserId is set
            foreach (var tip in careerTips)
            {
                tip.UserId = request.UserId;
            }

            // 8. Save career tips to DB
            _context.CareerTips.AddRange(careerTips);
            await _context.SaveChangesAsync();

            // 9. Return saved career tips
            return Ok(careerTips);
        }

        [HttpGet("{userId}")]
        public async Task<IActionResult> GetCareerTipsByUserId(int userId)
        {
            var careerTips = await _context.CareerTips
                .Where(ct => ct.UserId == userId)
                .ToListAsync();

            if (careerTips == null || !careerTips.Any())
                return NotFound(new { message = $"No Career Tips found for UserId {userId}" });

            return Ok(careerTips);
        }
    }

    public class GenerateCareerTipsRequest
    {
        public int UserId { get; set; }
        public int Count { get; set; } = 5;
    }
}
