//using Microsoft.AspNetCore.Mvc;
//using Microsoft.EntityFrameworkCore;
//using Newtonsoft.Json;
//using System.Net.Http;
//using System.Text;
//using InternConnect_Backend.Models;
//using InternConnect_Backend.Data;

//namespace Backend_InternPortal.Controllers
//{
//    [ApiController]
//    [Route("api/[controller]")]
//    public class CareerTipsController : ControllerBase
//    {
//        private readonly ApplicationDbContext _context;
//        private readonly IHttpClientFactory _httpClientFactory;
//        private readonly IConfiguration _config;

//        public CareerTipsController(ApplicationDbContext context, IHttpClientFactory httpClientFactory, IConfiguration config)
//        {
//            _context = context;
//            _httpClientFactory = httpClientFactory;
//            _config = config;
//        }

//        [HttpPost("generate")]
//        public async Task<IActionResult> GenerateCareerTips([FromBody] GenerateCareerTipsRequest request)
//        {
//            // 1. Fetch complete profile
//            var profile = await _context.Profiles
//                .Include(p => p.Educations)
//                .Include(p => p.Skills)
//                .Include(p => p.Projects)
//                .Include(p => p.Achievements)
//                .FirstOrDefaultAsync(p => p.UserId == request.UserId);

//            if (profile == null)
//                return NotFound("Profile not found for given UserId");

//            // 🔹 Remove existing career tips for this user
//            var existingTips = _context.CareerTips.Where(ct => ct.UserId == request.UserId);
//            if (existingTips.Any())
//            {
//                _context.CareerTips.RemoveRange(existingTips);
//                await _context.SaveChangesAsync();
//            }

//            // 2. Serialize profile safely
//            var profileJson = JsonConvert.SerializeObject(profile,
//                Formatting.None,
//                new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });

//            // 3. Build user prompt
//            var userPrompt = $@"
//Generate {request.Count} career tips for the following profile.
//Each tip must follow this JSON schema and tip should have 10 to 15 words and keep CareerTipId = 0 every time :

//[
//  {{
//    ""CareerTipId"": 0,
//    ""UserId"": {request.UserId},
//    ""Description"": ""string""
//  }}
//]

//Profile Data: {profileJson}
//Career Goal: {profile.CareerGoal}
//";

//            // 4. Call Gemini API
//            var geminiUrl = $"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={_config["Gemini:ApiKey"]}";

//            var payload = new
//            {
//                contents = new[]
//                {
//                    new
//                    {
//                        parts = new[]
//                        {
//                            new { text = userPrompt }
//                        }
//                    }
//                }
//            };

//            var httpClient = _httpClientFactory.CreateClient();
//            var httpContent = new StringContent(JsonConvert.SerializeObject(payload), Encoding.UTF8, "application/json");

//            var response = await httpClient.PostAsync(geminiUrl, httpContent);

//            if (!response.IsSuccessStatusCode)
//            {
//                var errorBody = await response.Content.ReadAsStringAsync();
//                return StatusCode((int)response.StatusCode, $"Failed to generate career tips from Gemini API. Response: {errorBody}");
//            }

//            var responseString = await response.Content.ReadAsStringAsync();
//            dynamic geminiResponse = JsonConvert.DeserializeObject(responseString);

//            if (geminiResponse?.candidates == null || geminiResponse.candidates.Count == 0)
//                return BadRequest("No career tips generated by Gemini");

//            string aiContent = geminiResponse.candidates[0].content.parts[0].text.ToString();

//            // 5. Clean AI response (strip ```json fences if present)
//            aiContent = aiContent.Trim();
//            if (aiContent.StartsWith("```"))
//            {
//                int firstNewLine = aiContent.IndexOf('\n');
//                int lastFence = aiContent.LastIndexOf("```");
//                if (firstNewLine >= 0 && lastFence > firstNewLine)
//                    aiContent = aiContent.Substring(firstNewLine + 1, lastFence - firstNewLine - 1).Trim();
//            }

//            // 6. Deserialize into CareerTips
//            List<CareerTip>? careerTips;
//            try
//            {
//                careerTips = JsonConvert.DeserializeObject<List<CareerTip>>(aiContent);
//            }
//            catch (JsonException ex)
//            {
//                return BadRequest("Failed to parse career tips from Gemini response. AI response: " + aiContent + " | Error: " + ex.Message);
//            }

//            if (careerTips == null || !careerTips.Any())
//                return BadRequest("No career tips parsed from AI response");

//            // 7. Ensure UserId is set
//            foreach (var tip in careerTips)
//            {
//                tip.UserId = request.UserId;
//            }

//            // 8. Save career tips to DB
//            _context.CareerTips.AddRange(careerTips);
//            await _context.SaveChangesAsync();

//            // 9. Return saved career tips
//            return Ok(careerTips);
//        }

//        [HttpGet("{userId}")]
//        public async Task<IActionResult> GetCareerTipsByUserId(int userId)
//        {
//            var careerTips = await _context.CareerTips
//                .Where(ct => ct.UserId == userId)
//                .ToListAsync();

//            if (careerTips == null || !careerTips.Any())
//                return NotFound(new { message = $"No Career Tips found for UserId {userId}" });

//            return Ok(careerTips);
//        }
//    }

//    public class GenerateCareerTipsRequest
//    {
//        public int UserId { get; set; }
//        public int Count { get; set; } = 5;
//    }
//}



using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;
using InternConnect_Backend.Models;
using InternConnect_Backend.Data;
using System.Text.RegularExpressions;

namespace Backend_InternPortal.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class CareerTipsController : ControllerBase
    {
        private readonly ApplicationDbContext _context;
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly IConfiguration _config;

        public CareerTipsController(ApplicationDbContext context, IHttpClientFactory httpClientFactory, IConfiguration config)
        {
            _context = context;
            _httpClientFactory = httpClientFactory;
            _config = config;
        }

        [HttpPost("generate")]
        public async Task<IActionResult> GenerateCareerTips([FromBody] GenerateCareerTipsRequest request)
        {
            // 1. Fetch complete profile
            var profile = await _context.Profiles
                .Include(p => p.Educations)
                .Include(p => p.Skills)
                .Include(p => p.Projects)
                .Include(p => p.Achievements)
                .FirstOrDefaultAsync(p => p.UserId == request.UserId);

            if (profile == null)
                return NotFound("Profile not found for given UserId");

            // 🔹 Remove existing career tips for this user
            var existingTips = _context.CareerTips.Where(ct => ct.UserId == request.UserId);
            if (existingTips.Any())
            {
                _context.CareerTips.RemoveRange(existingTips);
                await _context.SaveChangesAsync();
            }

            // 2. Serialize profile safely
            var profileJson = JsonConvert.SerializeObject(profile,
                Formatting.None,
                new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });

            // 3. Extract career goals
            var careerGoals = ExtractCareerGoals(profile.CareerGoal);
            var tipsPerGoal = careerGoals.Count > 0 ? (int)Math.Ceiling((double)request.Count / careerGoals.Count) : request.Count;

            // 4. Build user prompt for each career goal
            List<CareerTip> allCareerTips = new List<CareerTip>();

            foreach (var goal in careerGoals)
            {
                var userPrompt = $@"
Generate {tipsPerGoal} unique motivational tips for the following profile, focusing on this career goal: {goal}.  

Each tip should be uplifting, positive, and have the essence of a motivational quote, while staying relevant to the career goal.  

Each tip must strictly follow this JSON schema:  
[
  {{
    ""CareerTipId"": 0,
    ""UserId"": {request.UserId},
    ""Description"": ""string (10–15 words, motivational, inspiring, career-goal aligned)""
  }}
]

Profile Data: {profileJson}
Career Goal: {goal}

Guidelines:
- Ensure each tip has between 10 to 15 words.  
- Write in a motivational tone, like short inspiring advice or quotes.  
- Avoid repetition, make each tip unique.  
- Blend motivation with career growth essence naturally.  
";


                // 5. Call Gemini API
                var geminiUrl = $"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={_config["Gemini:ApiKey"]}";

                var payload = new
                {
                    contents = new[]
                    {
                    new
                    {
                        parts = new[]
                        {
                            new { text = userPrompt }
                        }
                    }
                }
                };

                var httpClient = _httpClientFactory.CreateClient();
                var httpContent = new StringContent(JsonConvert.SerializeObject(payload), Encoding.UTF8, "application/json");

                var response = await httpClient.PostAsync(geminiUrl, httpContent);

                if (!response.IsSuccessStatusCode)
                {
                    var errorBody = await response.Content.ReadAsStringAsync();
                    return StatusCode((int)response.StatusCode, $"Failed to generate career tips from Gemini API. Response: {errorBody}");
                }

                var responseString = await response.Content.ReadAsStringAsync();
                dynamic geminiResponse = JsonConvert.DeserializeObject(responseString);

                if (geminiResponse?.candidates == null || geminiResponse.candidates.Count == 0)
                    return BadRequest("No career tips generated by Gemini");

                string aiContent = geminiResponse.candidates[0].content.parts[0].text.ToString();

                // 5. Clean AI response (strip ```json fences if present)
                aiContent = aiContent.Trim();
                if (aiContent.StartsWith("```"))
                {
                    int firstNewLine = aiContent.IndexOf('\n');
                    int lastFence = aiContent.LastIndexOf("```");
                    if (firstNewLine >= 0 && lastFence > firstNewLine)
                        aiContent = aiContent.Substring(firstNewLine + 1, lastFence - firstNewLine - 1).Trim();
                }

                // 6. Deserialize into CareerTips
                List<CareerTip>? careerTips;
                try
                {
                    careerTips = JsonConvert.DeserializeObject<List<CareerTip>>(aiContent);
                }
                catch (JsonException ex)
                {
                    return BadRequest("Failed to parse career tips from Gemini response. AI response: " + aiContent + " | Error: " + ex.Message);
                }

                if (careerTips == null || !careerTips.Any())
                    return BadRequest("No career tips parsed from AI response");

                // 7. Ensure UserId is set and add to all tips
                foreach (var tip in careerTips)
                {
                    tip.UserId = request.UserId;
                }

                allCareerTips.AddRange(careerTips);

                // If we have enough tips, break early
                if (allCareerTips.Count >= request.Count)
                    break;
            }

            // 8. Limit to requested count and ensure uniqueness
            var uniqueTips = allCareerTips
                .GroupBy(t => t.Description)
                .Select(g => g.First())
                .Take(request.Count)
                .ToList();

            // 9. Save career tips to DB
            _context.CareerTips.AddRange(uniqueTips);
            await _context.SaveChangesAsync();

            // 10. Return saved career tips
            return Ok(uniqueTips);
        }

        [HttpGet("{userId}")]
        public async Task<IActionResult> GetCareerTipsByUserId(int userId)
        {
            var careerTips = await _context.CareerTips
                .Where(ct => ct.UserId == userId)
                .ToListAsync();

            if (careerTips == null || !careerTips.Any())
                return NotFound(new { message = $"No Career Tips found for UserId {userId}" });

            return Ok(careerTips);
        }

        // Helper method to extract multiple career goals from a string
        private List<string> ExtractCareerGoals(string careerGoalText)
        {
            var goals = new List<string>();

            if (string.IsNullOrEmpty(careerGoalText))
                return goals;

            // Split by common separators
            var separators = new[] { ",", ";", "and", "&", "/", "|" };
            var regexPattern = string.Join("|", separators.Select(s => Regex.Escape(s)));

            var splitGoals = Regex.Split(careerGoalText, regexPattern, RegexOptions.IgnoreCase)
                .Select(g => g.Trim())
                .Where(g => !string.IsNullOrEmpty(g))
                .ToList();

            return splitGoals.Any() ? splitGoals : new List<string> { careerGoalText.Trim() };
        }
    }

    public class GenerateCareerTipsRequest
    {
        public int UserId { get; set; }
        public int Count { get; set; } = 5;
    }
}