//using Microsoft.AspNetCore.Mvc;
//using Newtonsoft.Json;
//using System.Net.Http;
//using System.Text;
//using InternConnect_Backend.Models;
//using Microsoft.Extensions.Configuration;

//namespace Backend_InternPortal.Controllers
//{
//    [ApiController]
//    [Route("api/[controller]")]
//    public class ChatbotController : ControllerBase
//    {
//        private readonly IHttpClientFactory _httpClientFactory;
//        private readonly IConfiguration _config;

//        public ChatbotController(IHttpClientFactory httpClientFactory, IConfiguration config)
//        {
//            _httpClientFactory = httpClientFactory;
//            _config = config;
//        }

//        [HttpPost("chat")]
//        public async Task<IActionResult> ChatWithBot([FromBody] ChatRequest request)
//        {
//            if (string.IsNullOrWhiteSpace(request.Text))
//                return BadRequest("Text cannot be empty.");

//            // 1. Build prompt
//            var userPrompt = $@"
//You are a helpful career development assistant chatbot.
//The user with ID {request.UserId} sent the following message:
//""{request.Text}""

//Provide a helpful, concise, and polite response.";

//            // 2. Call Gemini API
//            var geminiUrl = $"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={_config["Gemini:ApiKey"]}";

//            var payload = new
//            {
//                contents = new[]
//                {
//                    new
//                    {
//                        parts = new[]
//                        {
//                            new { text = userPrompt }
//                        }
//                    }
//                }
//            };

//            var httpClient = _httpClientFactory.CreateClient();
//            var httpContent = new StringContent(JsonConvert.SerializeObject(payload), Encoding.UTF8, "application/json");

//            var response = await httpClient.PostAsync(geminiUrl, httpContent);

//            if (!response.IsSuccessStatusCode)
//            {
//                var errorBody = await response.Content.ReadAsStringAsync();
//                return StatusCode((int)response.StatusCode, $"Failed to generate response from Gemini API. Response: {errorBody}");
//            }

//            var responseString = await response.Content.ReadAsStringAsync();
//            dynamic geminiResponse = JsonConvert.DeserializeObject(responseString);

//            if (geminiResponse?.candidates == null || geminiResponse.candidates.Count == 0)
//                return BadRequest("No response generated by Gemini");

//            string aiContent = geminiResponse.candidates[0].content.parts[0].text.ToString();

//            // 3. Clean AI response (strip ```json or other formatting if present)
//            aiContent = aiContent.Trim();
//            if (aiContent.StartsWith("```"))
//            {
//                int firstNewLine = aiContent.IndexOf('\n');
//                int lastFence = aiContent.LastIndexOf("```");
//                if (firstNewLine >= 0 && lastFence > firstNewLine)
//                    aiContent = aiContent.Substring(firstNewLine + 1, lastFence - firstNewLine - 1).Trim();
//            }

//            // 4. Return the response
//            return Ok(new { reply = aiContent });
//        }
//    }

//    public class ChatRequest
//    {
//        public int UserId { get; set; }
//        public string Text { get; set; }
//    }
//}














using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;
using InternConnect_Backend.Models;
using Microsoft.Extensions.Configuration;

namespace Backend_InternPortal.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class ChatbotController : ControllerBase
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly IConfiguration _config;

        public ChatbotController(IHttpClientFactory httpClientFactory, IConfiguration config)
        {
            _httpClientFactory = httpClientFactory;
            _config = config;
        }

        [HttpPost("chat")]
        public async Task<IActionResult> ChatWithBot([FromBody] ChatHistoryRequest request)
        {
            if (request.Messages == null || request.Messages.Count == 0)
                return BadRequest("Messages cannot be empty.");

            // 1. Build conversation history
            var conversation = "";
            foreach (var msg in request.Messages)
            {
                if (msg.Sender == "user")
                    conversation += $"User: {msg.Text}\n";
                else if (msg.Sender == "bot")
                    conversation += $"Bot: {msg.Text}\n";
            }

            var userPrompt = $@"
You are a helpful career development assistant chatbot.
Continue the conversation based on the chat history below and respond politely.

Conversation history:
{conversation}

Bot:";

            // 2. Call Gemini API
            var geminiUrl = $"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={_config["Gemini:ApiKey"]}";

            var payload = new
            {
                contents = new[]
                {
                    new
                    {
                        parts = new[]
                        {
                            new { text = userPrompt }
                        }
                    }
                }
            };

            var httpClient = _httpClientFactory.CreateClient();
            var httpContent = new StringContent(JsonConvert.SerializeObject(payload), Encoding.UTF8, "application/json");

            var response = await httpClient.PostAsync(geminiUrl, httpContent);

            if (!response.IsSuccessStatusCode)
            {
                var errorBody = await response.Content.ReadAsStringAsync();
                return StatusCode((int)response.StatusCode, $"Failed to generate response from Gemini API. Response: {errorBody}");
            }

            var responseString = await response.Content.ReadAsStringAsync();
            dynamic geminiResponse = JsonConvert.DeserializeObject(responseString);

            if (geminiResponse?.candidates == null || geminiResponse.candidates.Count == 0)
                return BadRequest("No response generated by Gemini");

            string aiContent = geminiResponse.candidates[0].content.parts[0].text.ToString();

            aiContent = aiContent.Trim();
            if (aiContent.StartsWith("```"))
            {
                int firstNewLine = aiContent.IndexOf('\n');
                int lastFence = aiContent.LastIndexOf("```");
                if (firstNewLine >= 0 && lastFence > firstNewLine)
                    aiContent = aiContent.Substring(firstNewLine + 1, lastFence - firstNewLine - 1).Trim();
            }

            return Ok(new { reply = aiContent });
        }
    }

    public class ChatHistoryRequest
    {
        public int UserId { get; set; }
        public List<MessageEntry> Messages { get; set; }
    }

    public class MessageEntry
    {
        public string Sender { get; set; }
        public string Text { get; set; }
    }
}
