using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;
using InternConnect_Backend.Models;
using InternConnect_Backend.Data;

namespace InternConnect_Backend.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class MarketTrendAnalysisController : ControllerBase
    {
        private readonly ApplicationDbContext _context;
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly IConfiguration _config;

        public MarketTrendAnalysisController(ApplicationDbContext context, IHttpClientFactory httpClientFactory, IConfiguration config)
        {
            _context = context;
            _httpClientFactory = httpClientFactory;
            _config = config;
        }

        // Generate or refresh market trends
        [HttpPost("generate")]
        public async Task<IActionResult> GenerateMarketTrends([FromBody] GenerateTrendsRequest request)
        {
            if (request.UserId <= 0)
                return BadRequest("UserId is required.");

            // Check if last refresh was less than 24 hours ago
            var lastTrend = await _context.MarketTrendAnalyses
                .Where(t => t.UserId == request.UserId)
                .OrderByDescending(t => t.CreatedAt)
                .FirstOrDefaultAsync();

            if (lastTrend != null && (DateTime.UtcNow - lastTrend.CreatedAt).TotalHours < 24)
            {
                var existingTrends = await _context.MarketTrendAnalyses
                    .Where(t => t.UserId == request.UserId)
                    .ToListAsync();
                return Ok(existingTrends);
            }

            // Delete old trends before regenerating
            var oldTrends = _context.MarketTrendAnalyses.Where(t => t.UserId == request.UserId);
            if (oldTrends.Any())
            {
                _context.MarketTrendAnalyses.RemoveRange(oldTrends);
                await _context.SaveChangesAsync();
            }

            // Build Gemini API prompt
            var userPrompt = $@"
Generate {request.Count} market trend analyses for the user.
Each trend should follow this JSON schema:

[
  {{
    ""TrendId"": 0,
    ""UserId"": {request.UserId},
    ""Title"": ""string"",
    ""Description"": ""string"",
    ""Industry"": ""string"",
    ""Growth"": ""string"",
    ""SalaryTrend"": ""string"",
    ""Locations"": [""string""],
    ""Tags"": [""string""]
  }}
]
";

            var geminiUrl = $"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={_config["Gemini:ApiKey"]}";

            var payload = new
            {
                contents = new[] { new { parts = new[] { new { text = userPrompt } } } }
            };

            var httpClient = _httpClientFactory.CreateClient();
            var httpContent = new StringContent(JsonConvert.SerializeObject(payload), Encoding.UTF8, "application/json");
            var response = await httpClient.PostAsync(geminiUrl, httpContent);

            if (!response.IsSuccessStatusCode)
            {
                var errorBody = await response.Content.ReadAsStringAsync();
                return StatusCode((int)response.StatusCode, $"Failed to generate trends. Response: {errorBody}");
            }

            var responseString = await response.Content.ReadAsStringAsync();
            dynamic geminiResponse = JsonConvert.DeserializeObject(responseString);

            if (geminiResponse?.candidates == null || geminiResponse.candidates.Count == 0)
                return BadRequest("No trends generated by Gemini");

            string aiContent = geminiResponse.candidates[0].content.parts[0].text.ToString().Trim();

            // Clean AI response if wrapped in ``` blocks
            if (aiContent.StartsWith("```"))
            {
                int firstNewLine = aiContent.IndexOf('\n');
                int lastFence = aiContent.LastIndexOf("```");
                if (firstNewLine >= 0 && lastFence > firstNewLine)
                    aiContent = aiContent.Substring(firstNewLine + 1, lastFence - firstNewLine - 1).Trim();
            }

            List<MarketTrendAnalysis>? trends;
            try
            {
                trends = JsonConvert.DeserializeObject<List<MarketTrendAnalysis>>(aiContent);
            }
            catch (JsonException ex)
            {
                return BadRequest("Failed to parse trends from Gemini response. AI response: " + aiContent + " | Error: " + ex.Message);
            }

            if (trends == null || !trends.Any())
                return BadRequest("No trends parsed from AI response");

            // ====== Option 1: Set UserId, CreatedAt, and truncate string fields ======
            foreach (var trend in trends)
            {
                trend.TrendId = 0;
                trend.UserId = request.UserId;
                trend.CreatedAt = DateTime.UtcNow;

                // Truncate strings according to database column sizes
                trend.Title = Truncate(trend.Title, 100);
                trend.Description = Truncate(trend.Description, 500);
                trend.Industry = Truncate(trend.Industry, 100);
                trend.Growth = Truncate(trend.Growth, 100);
                trend.SalaryTrend = Truncate(trend.SalaryTrend, 100);

                // Optional: truncate lists if stored as JSON strings
                if (trend.Locations != null && trend.Locations.Count > 10)
                    trend.Locations = trend.Locations.Take(10).ToList();
                if (trend.Tags != null && trend.Tags.Count > 10)
                    trend.Tags = trend.Tags.Take(10).ToList();
            }

            // Save trends to DB
            _context.MarketTrendAnalyses.AddRange(trends);
            await _context.SaveChangesAsync();

            return Ok(trends);
        }

        [HttpGet("{userId}")]
        public async Task<IActionResult> GetTrendsByUser(int userId)
        {
            var trends = await _context.MarketTrendAnalyses
                .Where(t => t.UserId == userId)
                .ToListAsync();

            if (trends == null || !trends.Any())
                return NotFound(new { message = $"No market trends found for UserId {userId}" });

            return Ok(trends);
        }

        // ===== Helper method to truncate strings =====
        private string Truncate(string? value, int maxLength)
        {
            if (string.IsNullOrEmpty(value)) return string.Empty;
            return value.Length <= maxLength ? value : value.Substring(0, maxLength);
        }
    }

    public class GenerateTrendsRequest
    {
        public int UserId { get; set; }
        public int Count { get; set; } = 5;  // default 5 trends
    }
}
