using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;
using InternConnect_Backend.Models;
using InternConnect_Backend.Data;

namespace Backend_InternPortal.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class MockTestController : ControllerBase
    {
        private readonly ApplicationDbContext _context;
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly IConfiguration _config;

        public MockTestController(ApplicationDbContext context, IHttpClientFactory httpClientFactory, IConfiguration config)
        {
            _context = context;
            _httpClientFactory = httpClientFactory;
            _config = config;
        }

        // 🔹 POST: Generate 30 MCQs
        [HttpPost("generate")]
        public async Task<IActionResult> GenerateMockTest([FromBody] GenerateMockTestRequest request)
        {
            // 1. Fetch complete profile
            var profile = await _context.Profiles
                .Include(p => p.Educations)
                .Include(p => p.Skills)
                .Include(p => p.Projects)
                .Include(p => p.Achievements)
                .FirstOrDefaultAsync(p => p.UserId == request.UserId);

            if (profile == null)
                return NotFound("Profile not found for given UserId");

            // 2. Remove existing mock test questions for this user
            var existingQuestions = _context.MockTests.Where(mt => mt.UserId == request.UserId);
            if (existingQuestions.Any())
            {
                _context.MockTests.RemoveRange(existingQuestions);
                await _context.SaveChangesAsync();
            }

            // 3. Serialize profile safely
            var profileJson = JsonConvert.SerializeObject(profile,
                Formatting.None,
                new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });

            // 4. Build AI prompt
            var userPrompt = $@"
Generate {request.Count} multiple-choice questions (MCQs) for the following profile. 
Each question must strictly follow this JSON schema. 
Always keep QuestionId = 0 every time:

[
  {{
    ""QuestionId"": 0,
    ""UserId"": {request.UserId},
    ""QuestionNumber"": 1,
    ""Question"": ""string"",
    ""Option1"": ""string"",
    ""Option2"": ""string"",
    ""Option3"": ""string"",
    ""Option4"": ""string"",
    ""CorrectAnswer"": ""string"",
    ""Explanation"": ""string""
  }}
]

Profile Data: {profileJson}
Career Goal: {profile.CareerGoal}
";

            // 5. Call Gemini API
            var geminiUrl = $"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={_config["Gemini:ApiKey"]}";

            var payload = new
            {
                contents = new[]
                {
                    new
                    {
                        parts = new[]
                        {
                            new { text = userPrompt }
                        }
                    }
                }
            };

            var httpClient = _httpClientFactory.CreateClient();
            var httpContent = new StringContent(JsonConvert.SerializeObject(payload), Encoding.UTF8, "application/json");

            var response = await httpClient.PostAsync(geminiUrl, httpContent);

            if (!response.IsSuccessStatusCode)
            {
                var errorBody = await response.Content.ReadAsStringAsync();
                return StatusCode((int)response.StatusCode, $"Failed to generate mock test from Gemini API. Response: {errorBody}");
            }

            var responseString = await response.Content.ReadAsStringAsync();
            dynamic geminiResponse = JsonConvert.DeserializeObject(responseString);

            if (geminiResponse?.candidates == null || geminiResponse.candidates.Count == 0)
                return BadRequest("No mock test generated by Gemini");

            string aiContent = geminiResponse.candidates[0].content.parts[0].text.ToString();

            // 6. Clean AI response (strip ```json fences if present)
            aiContent = aiContent.Trim();
            if (aiContent.StartsWith("```"))
            {
                int firstNewLine = aiContent.IndexOf('\n');
                int lastFence = aiContent.LastIndexOf("```");
                if (firstNewLine >= 0 && lastFence > firstNewLine)
                    aiContent = aiContent.Substring(firstNewLine + 1, lastFence - firstNewLine - 1).Trim();
            }

            // 7. Deserialize into MockTest list
            List<MockTest>? mockTests;
            try
            {
                mockTests = JsonConvert.DeserializeObject<List<MockTest>>(aiContent);
            }
            catch (JsonException ex)
            {
                return BadRequest("Failed to parse mock test questions from Gemini response. AI response: " + aiContent + " | Error: " + ex.Message);
            }

            if (mockTests == null || !mockTests.Any())
                return BadRequest("No mock test questions parsed from AI response");

            // 8. Ensure UserId is set
            foreach (var q in mockTests)
            {
                q.UserId = request.UserId;
            }

            // 9. Save mock test questions to DB
            _context.MockTests.AddRange(mockTests);
            await _context.SaveChangesAsync();

            // 10. Return saved questions
            return Ok(mockTests);
        }

        // 🔹 GET: Get questions by UserId
        [HttpGet("{userId}")]
        public async Task<IActionResult> GetMockTestByUserId(int userId)
        {
            var mockTests = await _context.MockTests
                .Where(mt => mt.UserId == userId)
                .OrderBy(mt => mt.QuestionNumber)
                .ToListAsync();

            if (mockTests == null || !mockTests.Any())
                return NotFound(new { message = $"No MockTest questions found for UserId {userId}" });

            return Ok(mockTests);
        }
    }

    // Request model
    public class GenerateMockTestRequest
    {
        public int UserId { get; set; }
        public int Count { get; set; } = 30; // default 30 questions
    }
}
